import { Poppins } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Layout from "antd/es/layout/layout";
import { ConfigProvider } from "antd";

import { HeaderLayoutComponent,SideBar } from "@/components/layoutComponents";

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "#39C261",
              },
              components: {
                Button: {
                  colorPrimary: "#39C261",
                },
              },
            }}
          >
            <Layout style={{ width: "100vw", height: "100vh" }}>
              <SideBar />
              <Layout>
                <HeaderLayoutComponent />
                {children}
              </Layout>
            </Layout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
