import { Poppins } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Layout, { Content } from "antd/es/layout/layout";
import {
  Avatar,
  Badge,
  Button,
  ConfigProvider,
  Divider,
  Flex,
  Form,
  Input,
  Menu,

  Typography,
} from "antd";
import logo from "@/assets/images/logoipsum-285.svg";
import Image from "next/image";
import {
  AntDesignOutlined,
  AppstoreOutlined,
  BellOutlined,
  ContainerOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeploymentUnitOutlined,
  ExportOutlined,
  FileAddOutlined,
  FilterOutlined,
  LogoutOutlined,

  SearchOutlined,
  SettingOutlined,
  UserOutlined,
  UserSwitchOutlined,
} from "@ant-design/icons";
import Title from "antd/es/typography/Title";
import {TableData} from "@/components/layoutComponents/TableData";
import { SideBar } from "@/components/layoutComponents/SideBar";
import { Header } from "@/components/layoutComponents/Header";

const poppins = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "#000",
              },
              components:{
                Button:{
                  colorPrimary:"#39C261"
                }
              }
            }}
          >
            <Layout style={{width:"100vw",height:"100vh"}}>
<SideBar/>
              <Layout>
                {/* <Header
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    backgroundColor: "#FFF",
                  }}
                >
                  <Flex
                    justify="space-around"
                    align="center"
                    gap={10}
                    style={{ height: "100%", width: "60%" }}
                  >
                    <Input
                      placeholder="Search.."
                      prefix={<SearchOutlined />}
                      size="large"
                      style={{ width: "50%" }}
                    />
                    <p style={{ wordBreak: "none", whiteSpace: "nowrap" }}>
                      MONDAY,20th March 01:57 AM
                    </p>
                  </Flex>

                  <Flex align="center" gap={10} style={{ height: "100%" }}>
                    <Button
                      shape="default"
                      style={{ padding: "10px", display: "flex" }}
                    >
                      <Badge dot>
                        <BellOutlined />
                      </Badge>
                    </Button>
                    <Button
                      shape="default"
                      icon={<UserSwitchOutlined />}
                    ></Button>

                    <Divider
                      type="vertical"
                      style={{ height: "60%" }}
                      orientation="center"
                    />
                    <Avatar
                      size="large"
                      src={"https://picsum.photos/200/200"}
                    />
                    <Flex
                      vertical
                      justify="center"
                      align="center"
                      style={{ height: "100%" }}
                    >
                      <p style={{ marginBottom: "-22px", padding: 0 }}>
                        John Doe
                      </p>
                      <p style={{ marginTop: "-22px", padding: 0 }}>
                        Super Admin
                      </p>
                    </Flex>
                  </Flex>
                </Header> */}
<Header/>
                <Content
                  style={{
                    padding: "32px",
                    display: "flex",
                    flexDirection: "column",
                    gap: "20px",
                    justifyItems: "flex-start",
                    alignItems: "center",
                  }}
                >
                  <Flex
                    justify="space-between"
                    align="flex-start"
                    style={{ paddingTop: "2px", width: "100%" }}
                  >
                    <Title>Accessories</Title>
                    <Flex justify="flex-end" align="center" gap={10}>
                      <Button type="primary" size="large" icon={<ExportOutlined />}>
                        Export
                      </Button>
                      <Button size="large" icon={<FileAddOutlined />}>
                        Add New
                      </Button>
                    </Flex>
                  </Flex>
                  <Flex
                    vertical
                    gap={20}
                    style={{
                      padding: "24px",
                      width: "100%",
                      backgroundColor: "#FFF",
                      borderRadius: "24px",
                    }}
                  >
                    <Flex
                      justify="space-between"
                      align="center"
                      style={{ width: "100%" }}
                    >
                      <Input
                        placeholder="Search.."
                        prefix={<SearchOutlined />}
                        size="large"
                        style={{ width: "40%" }}
                      />
                      <Flex justify="flex-end" align="center" gap={10}>
                        <Button size="large" icon={<FilterOutlined />}>
                          Apply Filter
                        </Button>
                      </Flex>
                    </Flex>
                    <TableData/>
                  </Flex>
                </Content>
              </Layout>

              {children}
            </Layout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
